#!/bin/bash
#=======================================================================
cd ./Code/
echo "============================================================"
echo "RUNNING SCRIPT 1 OUT OF 13"
echo ""
echo ""
echo "Calculating the generator for Hydons_model."
echo "The results are stored in the folder:"
echo "Output"
echo "============================================================"
echo " "
echo ""
python3 launch_symmetry_calculations.py hydons_model 1
echo "============================================================"
echo "RUNNING SCRIPT 2 OUT OF 13"
echo ""
echo ""
echo "Calculating the generator for the DBH model."
echo "The results are stored in the folder:"
echo "Output"
echo "============================================================"
echo " "
echo ""
python3 launch_symmetry_calculations.py DBH_model 2
echo "============================================================"
echo "RUNNING SCRIPT 3 OUT OF 13"
echo ""
echo ""
echo "Calculating the generator for the DBH model."
echo "The results are stored in the folder:"
echo "Output"
echo "============================================================"
echo " "
echo ""
python3 launch_symmetry_calculations.py DBH_model 3
echo "============================================================"
echo "RUNNING SCRIPT 4 OUT OF 13"
echo ""
echo ""
echo "Calculating the generator for the AIDS epidemic model."
echo "The results are stored in the folder:"
echo "Output"
echo "============================================================"
echo " "
echo ""
python3 launch_symmetry_calculations.py AIDS_epidemic 3
echo "============================================================"
echo "RUNNING SCRIPT 5 OUT OF 13"
echo ""
echo ""
echo "Calculating the generator for the BZ model."
echo "The results are stored in the folder:"
echo "Output"
echo "============================================================"
echo " "
echo ""
python3 launch_symmetry_calculations.py BZ_model 3
echo "============================================================"
echo "RUNNING SCRIPT 6 OUT OF 13"
echo ""
echo ""
echo "Calculating the generator for the Goodwin version 1 model."
echo "The results are stored in the folder:"
echo "Output"
echo "============================================================"
echo " "
echo ""
python3 launch_symmetry_calculations.py Goodwin_1 3
echo "============================================================"
echo "RUNNING SCRIPT 7 OUT OF 13"
echo ""
echo ""
echo "Calculating the generator for the Goodwin version 2 model."
echo "The results are stored in the folder:"
echo "Output"
echo "============================================================"
echo " "
echo ""
python3 launch_symmetry_calculations.py Goodwin_2 3
echo "============================================================"
echo "RUNNING SCRIPT 8 OUT OF 13"
echo ""
echo ""
echo "Calculating the generator for the Lotka Volterra model."
echo "The results are stored in the folder:"
echo "Output"
echo "============================================================"
echo " "
echo ""
python3 launch_symmetry_calculations.py Lotka_Volterra 3
echo "============================================================"
echo "RUNNING SCRIPT 9 OUT OF 13"
echo ""
echo ""
echo "Calculating the generator for the Lotka Volterra realistic model."
echo "The results are stored in the folder:"
echo "Output"
echo "============================================================"
echo " "
echo ""
python3 launch_symmetry_calculations.py Lotka_Volterra_realistic 3
echo "============================================================"
echo "RUNNING SCRIPT 10 OUT OF 13"
echo ""
echo ""
echo "Calculating the generator for the Brusselator model."
echo "The results are stored in the folder:"
echo "Output"
echo "============================================================"
echo " "
echo ""
python3 launch_symmetry_calculations.py Brusselator 3
echo "============================================================"
echo "RUNNING SCRIPT 11 OUT OF 13"
echo ""
echo ""
echo "Calculating the generator for the Lactose_operon model."
echo "The results are stored in the folder:"
echo "Output"
echo "============================================================"
echo " "
echo ""
python3 launch_symmetry_calculations.py Lactose_operon 3
echo "============================================================"
echo "RUNNING SCRIPT 12 OUT OF 13"
echo ""
echo ""
echo "Calculating the generator for the Lorenz model."
echo "The results are stored in the folder:"
echo "Output"
echo "============================================================"
echo " "
echo ""
python3 launch_symmetry_calculations.py Lorenz_model 3
echo "============================================================"
echo "RUNNING SCRIPT 13 OUT OF 13"
echo ""
echo ""
echo "Calculating the generator for the SIR model."
echo "The results are stored in the folder:"
echo "Output"
echo "============================================================"
echo " "
echo ""
python3 launch_symmetry_calculations.py SIR 3
echo "============================================================"
echo "GENERATING REPORT"
echo ""
echo ""
echo "A summary report is generated in the Output folder"
echo "============================================================"
echo " "
echo ""
python3 generate_report.py
cd ../Output
pdflatex summary_report.tex
pdflatex summary_report.tex
echo "============================================================"
echo "EVERYTHING WAS EXECUTED SUCCESFULLY!"
echo ""
echo ""
echo "============================================================"
